FROM node:18.6-alpine as builder
WORKDIR /usr/mysecrets/client
COPY ./client/package.json .
RUN npm install --legacy-peer-deps
COPY ./client .
RUN npm run build

FROM nginx
COPY --from=builder /usr/mysecrets/client/build /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80